ts:
	g++ -g -O3 ts.cpp -o ts.out

ts_refactor:
	g++ -g --std=c++20 -O3 ts_refactor.cpp -o ts_refactor.out

tsp:
	g++ -g --std=c++26 -O3 tsp.cpp -o tsp.out

scratch:
	g++ -g --std=c++26 -O3 scratch.cpp -o scratch.out

