/* 
 * Eecs281 fall 2003 group 17 project 3 part 1
 *
 * Permutation generation based on code by: Igor Markov
 * Date:   Feb 12, 2002
 * New code generated by eecs281 group 17 fall 2003
 * Wednesday December 3, 2003 2:43 am finished
 *
 * Suggested use on linux machine: 
 *    []$ g++ p3_5.cpp -o test
 *    []$ ./test test.txt > ouput
 *
 * Where test.txt is the name of the input file
 * This will cause the cout statements to go to an output file
 * and all cerr statements will go to console
 */
#include <climits>
#include <queue>
#include <stack>
#include <iostream>
#include <cmath>
#include <cstdlib>
#include <string>
#include <fstream>

using namespace std;

// This library contains the point class. has x and y coordinates
#include "point.h"

typedef struct path
{
   double length;
   stack<point> points;
};

//global variables used to reduce function parameters
path minimum;
double rt2 = sqrt(3.);
double ** distances;
int numCities;

// Pythagorean theorem to find distance
double findDistance(point, point);

// Overloaded operator to use for outputing a stack of points
ostream& operator<<(ostream&, const stack<point>&);

// Generates all the permutations and prints out all perms and the 
// Distance of the paths each represents
void genPerms(queue<point>& , stack<point>& , const point &, /*int,*/ double);

int main(int argc, char *argv[])
{  
   ifstream fileIn;
   char* fileName;
   point* city;
   int length;
   point tmpPnt;
   point *temp;
   minimum.length = INT_MAX;
   double distanceThusFar = 0;
      
   // Check to see if input arguments were bad
   if (argc != 2) 
   {
      cout << "error: usage: <exe> <infile>" << argv[0] << endl;
      exit(1);
   }

   // arg[1] by convention of this program is the name of the file
   fileName = argv[1];
   
   fileIn.open(fileName);
   if(!fileIn.is_open())
   {cerr << "error opening file" << endl; exit(1);}
   
   // Store first two items in file as length of a side and number of cities
   fileIn >> length;
   fileIn >> numCities;
   
   // Array of all the points representing cities
   city = new point[numCities];
   
   stack<point> s;
   queue<point> q;
   
   int k=numCities;
   point firstCity;
   fileIn >> firstCity.x;
   fileIn >> firstCity.y;
   firstCity.pointNum = 1;
   
   for(;k!=1;--k) 
   {
      // read rest file here, storing each city into queue, instead of array
      // Iteratively move through file storing points in city
      fileIn >> tmpPnt.x;
      fileIn >> tmpPnt.y;
      tmpPnt.pointNum = numCities - k + 2;      
      
      q.push(tmpPnt);
      cout << tmpPnt.x << " " << tmpPnt.y << endl; 
   }

   // Turn the queue into a fully filled array
   temp = new point[numCities];
   queue<point> tempQ = q;
   temp[0]=firstCity;
   for(int i=1; i<numCities; ++i)
   {
       temp[i] = tempQ.front();
       tempQ.pop();
   }
   
   // Set up 2d dynamic array of doubles
   distances = new double*[numCities];
   for(int i=0; i<numCities; i++)
   {
       distances[i] = new double[numCities];
   }   
   
   // fill array using pythagorean thm and previously filled array
   for(int i=0; i<numCities; i++)
   {
       for(int j=0; j<numCities; j++)
       {
           distances[i][j] = findDistance(temp[i],temp[j]);
       }
   }

   genPerms(q, s, firstCity, /*numCities,*/ distanceThusFar);
   
   // Print out results
   cout << minimum.length << endl;
   cout << firstCity.pointNum << " ";
   cout << minimum.points; 
   cout << firstCity.pointNum << " " << endl;
   //cout << rt2 << endl;

return 0;
}


// on test input 15 pts, exectues 55,154,625 times
void genPerms(queue<point>& q, stack<point>& s, const point & firstCity,
              /*int numCities,*/ double distanceThusFar)
{
     int k=0, qsize=q.size();
     int ssize = s.size();
     point temp;

     if (!qsize) 
     {  
        distanceThusFar = distanceThusFar + 
           distances[s.top().pointNum-1][firstCity.pointNum-1];
        if(distanceThusFar < minimum.length)
        {
           minimum.length = distanceThusFar;
           minimum.points = s;
        
        }
     return;
     }

     //++paths;
     if(ssize > 0)
     {
        if(distanceThusFar + distances[s.top().pointNum-1][firstCity.pointNum-1]
           + rt2*(qsize-1) > minimum.length)
        {return;}
     }
     
     for(;k!=qsize;++k)
     {
         // if stack is empty, first item is being added
         if(s.empty())
         {temp = firstCity;}
         else
         {temp = s.top();}
         s.push(q.front());
         q.pop();          
         distanceThusFar = distanceThusFar + 
                           distances[temp.pointNum-1][s.top().pointNum-1];
     
         genPerms(q, s, firstCity, /*numCities,*/ distanceThusFar);
     
         temp = s.top();
         q.push(temp);
         s.pop();
         
         // first item readded to the queue, take off its distance
         if(s.empty())
         {
            distanceThusFar = distanceThusFar - 
                              distances[firstCity.pointNum-1][temp.pointNum-1];
         }
         else
         {   
            distanceThusFar = distanceThusFar - 
                              distances[s.top().pointNum-1][temp.pointNum-1];
         }
     }
}


// print the contents of a stack in one line
ostream& operator<<(ostream& out, const stack<point>& s)
{
  stack<point> tmpStack=s;  
  // tmpStack will be modified, while s is const
  
  while(tmpStack.size())
  {
     out << tmpStack.top().pointNum << " ";
     tmpStack.pop();
  }

return out;
}

// no need to optimize, all calls finish in a time not measured by computer
// Simple implementation of pythagorean theorem for the point class
double findDistance(point point1, point  point2)
{
// (a^2 + b^2)^.5 = c
return sqrt((double)((point1.x - point2.x) * (point1.x - point2.x) + 
            (point1.y - point2.y) * (point1.y - point2.y)));
}
